FROM python:3.9
WORKDIR /app

COPY requirements.txt ./Optimization/ExternalAPI/  ./
RUN pip install -r ./requirements.txt
#ENV FLASK_ENV production

EXPOSE 6001
CMD ["poetry", "run", "flask", "--app", "api_electricity" , "run", "--port=5001"]